### PR TITLE
Demo issue 2

### PR DESCRIPTION
**Pull request by McFoggy**
PR demonstrating #2

feel free to throw it away if #2 is not applicable.

### CODE REVIEW

**Comment by McFoggy** [comment]
under `envs\ee` I used `mvn -Pwildfly test` to launch tests that are of course failing currently.

**Comment by McFoggy** [comment]
pfff, was not as easy as I expected...

**Comment by McFoggy** [comment]
due to github outage, i'll push another squach commit to force travis to rebuild correclty

**Comment by astefanutti** [comment]
Awesome! Thanks.

**Pull request merged**
